# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.CharField(default='yup', max_length=255),
            preserve_default=False,
        ),
    ]
