# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_remove_wish_date_granted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
